"""Tests for table replication against published paper tables.
"""

import pytest
import pandas as pd
from pandas.testing import assert_frame_equal

from src._paths import TABLES_DIR
from src.create_table_replication import (
    create_table_3_1,
    create_table_3_2,
    create_table_3_3,
    create_table_3_5,
    create_table_3_6,
    create_table_3_7,
    create_table_3_8,
    create_table_3_9,
    create_table_3_11,
    create_table_3_12,
    create_table_3_13,
    create_table_3_15,
    create_table_3_16,
    create_table_4_1,
    create_table_D_1,
    create_table_D_2a,
    create_table_D_2b,
    create_table_D_2c,
    create_table_D_2d,
    create_table_E_1,
    create_table_E_2,
    create_table_E_5,
    create_table_E_10,
    create_table_F_1,
    create_table_F_2,
    create_table_F_3,
    create_table_F_4,
    create_table_F_5,
)

DATA_DIR = TABLES_DIR / 'auto_extracted'
GENERATED_DIR = TABLES_DIR / 'generated'

# Tables present in the paper but not generated by the pipeline (manually written).
# Excluded from the generated-vs-extracted comparison.
MANUALLY_WRITTEN_PREFIXES = (
    "Table_3.4.",
    "Table_3.14.",
    "Table_4.2.",
    "Table_5.1.",
    "Table_E.6.",
    "Table_E.11.",
    "Figure_3.2.",
    "Appendix_A.",
)


# =============================================================================
# TABLE 3.X TESTS - MAIN BODY
# =============================================================================


def test_table_3_1(expected_keywords_processed_df):
    """Table 3.1: Innovation Level by Cohort"""
    expected_3_1 = pd.read_excel(GENERATED_DIR / "Table_3.1._Evolution_of_Innovation_Intensity_in_Bank_Group_Projects_(5-Year_Cohorts,_1998–2025).xlsx")
    actual_3_1 = create_table_3_1(expected_keywords_processed_df)
    assert_frame_equal(expected_3_1, actual_3_1, check_dtype=True)


def test_table_3_2(expected_keywords_processed_df):
    """Table 3.2: HM Innovation Share by Cohort"""
    expected_3_2 = pd.read_excel(GENERATED_DIR / "Table_3.2._Contextualizing_the_Innovation_Intensity_of_Bank_Group_Projects_Over_Time.xlsx")
    actual_3_2 = create_table_3_2(expected_keywords_processed_df)
    assert_frame_equal(expected_3_2, actual_3_2, check_dtype=True)


def test_table_3_3(expected_keywords_processed_df):
    """Table 3.3: Pilot prevalence by cohort"""
    expected_3_3 = pd.read_excel(GENERATED_DIR / "Table_3.3._Innovation_Scaling_Patterns_in_World_Bank_Lending.xlsx")
    actual_3_3 = create_table_3_3(expected_keywords_processed_df)
    assert_frame_equal(expected_3_3, actual_3_3, check_dtype=True, check_categorical=True)


def test_table_3_5(expected_keywords_processed_df):
    """Table 3.5: Innovation type prevalence"""
    expected_3_5 = pd.read_excel(GENERATED_DIR / "Table_3.5._Prevalence_of_Innovation_Types_in_the_Innovation_PortfolioT.xlsx")
    actual_3_5 = create_table_3_5(expected_keywords_processed_df)
    assert_frame_equal(expected_3_5, actual_3_5, check_dtype=True)


def test_table_3_6(expected_keywords_processed_df):
    """Table 3.6: Innovation type prevalence by cohort"""
    expected_3_6 = pd.read_excel(GENERATED_DIR / "Table_3.6._Prevalence_of_Innovation_Types_by_Decade.xlsx")
    actual_3_6 = create_table_3_6(expected_keywords_processed_df)
    assert_frame_equal(expected_3_6, actual_3_6, check_dtype=True)


def test_table_3_7(expected_keywords_processed_df):
    """Table 3.7: Innovation by Region"""
    expected_3_7 = pd.read_excel(GENERATED_DIR / "Table_3.7._Innovation_Intensity_by_Region.xlsx")
    actual_3_7 = create_table_3_7(expected_keywords_processed_df)
    assert_frame_equal(expected_3_7, actual_3_7, check_dtype=True)


def test_table_3_8(expected_keywords_processed_df):
    """Table 3.8: Innovation by FCS"""
    expected_3_8 = pd.read_excel(GENERATED_DIR / "Table_3.8._Innovation_in_FCS_Contexts.xlsx")
    actual_3_8 = create_table_3_8(expected_keywords_processed_df)
    assert_frame_equal(expected_3_8, actual_3_8, check_dtype=True)


def test_table_3_9(expected_keywords_processed_df):
    """Table 3.9: Innovation by GP"""
    expected_3_9 = pd.read_excel(GENERATED_DIR / "Table_3.9._Sectoral_Patterns_of_Innovation_in_GPs.xlsx")
    actual_3_9 = create_table_3_9(expected_keywords_processed_df)
    assert_frame_equal(expected_3_9, actual_3_9, check_dtype=True)

def test_table_3_11(expected_keywords_processed_df):
    """Table 3.11: Outcome by technology presence"""
    expected_3_11 = pd.read_excel(GENERATED_DIR / "Table_3.11._Technology_Premium_Across_Projects.xlsx")
    actual_3_11 = create_table_3_11(expected_keywords_processed_df)
    assert_frame_equal(expected_3_11, actual_3_11, check_dtype=True)


def test_table_3_12(expected_keywords_processed_df):
    """Table 3.12: Tech premium by GP"""
    expected_3_12 = pd.read_excel(GENERATED_DIR / "Table_3.12._Technology_Premium_in_Projects_by_GP_(High_+_Moderate_Projects).xlsx")
    actual_3_12 = create_table_3_12(expected_keywords_processed_df)
    assert_frame_equal(expected_3_12, actual_3_12, check_dtype=True)

def test_table_3_13(expected_keywords_processed_df):
    """Table 3.13: Innovation by IFC mention"""
    expected_3_13 = pd.read_excel(GENERATED_DIR / "Table_3.13._Projects_with_IFC_Collaboration.xlsx")
    actual_3_13 = create_table_3_13(expected_keywords_processed_df)
    assert_frame_equal(expected_3_13, actual_3_13, check_dtype=True)

def test_table_3_15(expected_keywords_processed_df):
    """Table 3.15: Innovation by PCM mention"""
    expected_3_15 = pd.read_excel(GENERATED_DIR / "Table_3.15._PCM_Projects.xlsx")
    actual_3_15 = create_table_3_15(expected_keywords_processed_df)
    assert_frame_equal(expected_3_15, actual_3_15, check_dtype=True)


def test_table_3_16(expected_keywords_processed_df):
    """Table 3.16: Innovation by PCM and GP"""
    expected_3_16 = pd.read_excel(GENERATED_DIR / "Table_3.16._Sectors_with_Active_PCM.xlsx")
    actual_3_16 = create_table_3_16(expected_keywords_processed_df)
    assert_frame_equal(expected_3_16, actual_3_16, check_dtype=True)


# =============================================================================
# TABLE 4.X TESTS - PILOT AND SCALE
# =============================================================================
def test_table_4_1(expected_keywords_processed_df):
    """Table 4.1: Outcome rating by pilot & scale"""
    expected_4_1 = pd.read_excel(GENERATED_DIR / "Table_4.1._Importance_of_Context-Appropriate_Innovation.xlsx")
    actual_4_1 = create_table_4_1(expected_keywords_processed_df)
    assert_frame_equal(expected_4_1, actual_4_1, check_dtype=True)


# =============================================================================
# APPENDIX D TESTS
# =============================================================================

def test_table_D_1(expected_keywords_processed_df):
    """Table D.1: Projects by Innovation"""
    expected_D1 = pd.read_excel(GENERATED_DIR / "Table_D.1._Distribution_of_Innovation_in_WBG_portfolio.xlsx")
    actual_D1 = create_table_D_1(expected_keywords_processed_df)
    assert_frame_equal(expected_D1, actual_D1, check_dtype=True)

def test_table_D_2a(expected_keywords_processed_df):
    """Table D.2a: Outcome by Innovation"""
    expected_D2a = pd.read_excel(GENERATED_DIR / "Table_D.2a._Innovation_Premium_Across_Projects_-.xlsx")
    actual_D2a = create_table_D_2a(expected_keywords_processed_df)
    assert_frame_equal(expected_D2a, actual_D2a, check_dtype=True)

def test_table_D_2b(expected_keywords_processed_df):
    """Table D.2b: Bank Performance Ratings"""
    expected_D2b = pd.read_excel(GENERATED_DIR / "Table_D.2b._Innovation_Premium_Across_Projects_–_Bank_Performance_Rating.xlsx")
    actual_D2b = create_table_D_2b(expected_keywords_processed_df)
    assert_frame_equal(expected_D2b, actual_D2b, check_dtype=True)

def test_table_D_2c(expected_keywords_processed_df):
    """Table D.2c: Quality of supervision Ratings"""
    expected_D2c = pd.read_excel(GENERATED_DIR / "Table_D.2c._Innovation_Premium_Across_Projects_–_Quality_of_Supervision_Rating.xlsx")
    actual_D2c = create_table_D_2c(expected_keywords_processed_df)
    assert_frame_equal(expected_D2c, actual_D2c, check_dtype=True)

def test_table_D_2d(expected_keywords_processed_df):
    """Table D.2d: Quality at entry Ratings"""
    expected_D2d = pd.read_excel(GENERATED_DIR / "Table_D.2d._Innovation_Premium_Across_Projects_–_Quality_at_Entry_Rating.xlsx")
    actual_D2d = create_table_D_2d(expected_keywords_processed_df)
    assert_frame_equal(expected_D2d, actual_D2d, check_dtype=True)
    
# =============================================================================
# APPENDIX E TESTS - INNOVATION MODELS
# =============================================================================

def test_table_E_1(expected_keywords_processed_df):
    """Table E.1: Innovation Models Frequency"""
    expected_E_1 = pd.read_excel(GENERATED_DIR / "Table_E.1._Selected_Examples_of_Innovation_Models_Generated_Based_on_the_Analytics.xlsx")
    actual_E_1 = create_table_E_1(expected_keywords_processed_df)
    assert_frame_equal(expected_E_1, actual_E_1, check_dtype=True)


def test_table_E_2(expected_keywords_processed_df):
    """Table E.2: Top 4 innovation models by decade"""
    expected_E_2 = pd.read_excel(GENERATED_DIR / "Table_E.2._Top_Four_Innovation_Models_by_Decade.xlsx")
    actual_E_2 = create_table_E_2(expected_keywords_processed_df)
    assert_frame_equal(expected_E_2, actual_E_2, check_dtype=True)


def test_table_E_5(expected_keywords_processed_df):
    """Table E.5: PPP share by decade"""
    expected_E_5 = pd.read_excel(GENERATED_DIR / "Table_E.5._Diffusion_of_PPP_Model_Over_Time.xlsx")
    actual_E_5 = create_table_E_5(expected_keywords_processed_df)
    assert_frame_equal(expected_E_5, actual_E_5, check_dtype=True)


def test_table_E_10(expected_keywords_processed_df):
    """Table E.10: CDD share by decade"""
    expected_E_10 = pd.read_excel(GENERATED_DIR / "Table_E.10._Diffusion_of_CDD_Model_Over_Time.xlsx")
    actual_E_10 = create_table_E_10(expected_keywords_processed_df)
    assert_frame_equal(expected_E_10, actual_E_10, check_dtype=True)


# =============================================================================
# APPENDIX F TESTS - FCS ANALYSIS
# =============================================================================

def test_table_F_1(expected_keywords_processed_df):
    """Table F.1: Models by FCS"""
    expected_F_1 = pd.read_excel(GENERATED_DIR / "Table_F.1._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS.xlsx")
    actual_F_1 = create_table_F_1(expected_keywords_processed_df)
    assert_frame_equal(expected_F_1, actual_F_1, check_dtype=False)


def test_table_F_2(expected_keywords_processed_df):
    """Table F.2: CCT FCS by decade"""
    expected_F_2 = pd.read_excel(GENERATED_DIR / "Table_F.2._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_Conditional_Cash_Transfers.xlsx")
    actual_F_2 = create_table_F_2(expected_keywords_processed_df)
    assert_frame_equal(expected_F_2, actual_F_2, check_dtype=True)


def test_table_F_3(expected_keywords_processed_df):
    """Table F.3: PPP FCS by decade"""
    expected_F_3 = pd.read_excel(GENERATED_DIR / "Table_F.3._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_PPP.xlsx")
    actual_F_3 = create_table_F_3(expected_keywords_processed_df)
    assert_frame_equal(expected_F_3, actual_F_3, check_dtype=True)


def test_table_F_4(expected_keywords_processed_df):
    """Table F.4: E-procurement FCS by decade"""
    expected_F_4 = pd.read_excel(GENERATED_DIR / "Table_F.4._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_E-Procurement.xlsx")
    actual_F_4 = create_table_F_4(expected_keywords_processed_df)
    assert_frame_equal(expected_F_4, actual_F_4, check_dtype=True)


def test_table_F_5(expected_keywords_processed_df):
    """Table F.5: CDD FCS by decade"""
    expected_F_5 = pd.read_excel(GENERATED_DIR / "Table_F.5._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_CDD.xlsx")
    actual_F_5 = create_table_F_5(expected_keywords_processed_df)
    assert_frame_equal(expected_F_5, actual_F_5, check_dtype=True)


# =============================================================================
# GENERATED vs EXTRACTED
# =============================================================================

@pytest.fixture(scope='session')
def refresh_auto_extracted():
    """Re-extract tables from the Word doc into auto_extracted/ before comparing."""
    from tests.table_extractor import main as run_extractor
    run_extractor()


def _is_manually_written(filename: str) -> bool:
    return any(filename.startswith(prefix) for prefix in MANUALLY_WRITTEN_PREFIXES)


def _extracted_table_pairs():
    """Yield (extracted, generated) path pairs for pipeline-generated tables only."""
    if not DATA_DIR.exists():
        return []
    return [
        pytest.param(ae, GENERATED_DIR / ae.name, id=ae.stem)
        for ae in sorted(DATA_DIR.glob("*.xlsx"))
        if not _is_manually_written(ae.name)
    ]


@pytest.mark.parametrize("extracted,generated", _extracted_table_pairs())
def test_generated_matches_extracted(refresh_auto_extracted, extracted, generated):
    """Verify each pipeline-generated table matches the paper (auto_extracted/)."""
    assert generated.exists(), f"Missing in generated/: {generated.name}"
    assert_frame_equal(pd.read_excel(extracted), pd.read_excel(generated), check_dtype=True)


def test_no_extra_generated_tables(refresh_auto_extracted):
    """Verify generated/ contains no tables absent from the paper (auto_extracted/)."""
    extracted_names = {f.name for f in DATA_DIR.glob("*.xlsx")}
    extras = sorted(
        f.name for f in GENERATED_DIR.glob("*.xlsx")
        if f.name not in extracted_names
    )
    assert not extras, (
        f"Tables in generated/ not found in auto_extracted/ (not in paper?):\n"
        + "\n".join(f"  {name}" for name in extras)
    )


def test_no_manually_written_tables_in_generated():
    """Verify generated/ contains no manually-written tables.

    Manually-written tables are not produced by the pipeline and must not
    appear in generated/. This guards against accidental copies from the
    paper (e.g. via LLM output or manual editing).
    """
    offenders = sorted(
        f.name for f in GENERATED_DIR.glob("*.xlsx")
        if _is_manually_written(f.name)
    )
    assert not offenders, (
        "Manually-written tables found in generated/ — these are not pipeline outputs "
        "and should be removed:\n"
        + "\n".join(f"  {name}" for name in offenders)
    )
