from src.create_table_replication import (
    create_table_3_1, create_table_3_2, create_table_3_3, create_table_3_5,
    create_table_3_6, create_table_3_7, create_table_3_8, create_table_3_9,
    create_table_3_11, create_table_3_12, create_table_3_13, create_table_3_15, create_table_3_16,
    create_table_4_1,
    create_table_D_1, create_table_D_2a, create_table_D_2b, create_table_D_2c, create_table_D_2d,
    create_table_E_1, create_table_E_2, create_table_E_5, create_table_E_10,
    create_table_F_1, create_table_F_2, create_table_F_3, create_table_F_4, create_table_F_5,
)

# Maps each table-generating function to (output filename, use_first_col_for_comparison).
TABLE_REPLICATION_MAP = {
    create_table_3_1:  ("Table_3.1._Evolution_of_Innovation_Intensity_in_Bank_Group_Projects_(5-Year_Cohorts,_1998–2025).xlsx", True),
    create_table_3_2:  ("Table_3.2._Contextualizing_the_Innovation_Intensity_of_Bank_Group_Projects_Over_Time.xlsx", True),
    create_table_3_3:  ("Table_3.3._Innovation_Scaling_Patterns_in_World_Bank_Lending.xlsx", True),
    create_table_3_5:  ("Table_3.5._Prevalence_of_Innovation_Types_in_the_Innovation_PortfolioT.xlsx", True),
    create_table_3_6:  ("Table_3.6._Prevalence_of_Innovation_Types_by_Decade.xlsx", True),
    create_table_3_7:  ("Table_3.7._Innovation_Intensity_by_Region.xlsx", True),
    create_table_3_8:  ("Table_3.8._Innovation_in_FCS_Contexts.xlsx", True),
    create_table_3_9:  ("Table_3.9._Sectoral_Patterns_of_Innovation_in_GPs.xlsx", True),
    create_table_3_11: ("Table_3.11._Technology_Premium_Across_Projects.xlsx", True),
    create_table_3_12: ("Table_3.12._Technology_Premium_in_Projects_by_GP_(High_+_Moderate_Projects).xlsx", True),
    create_table_3_13: ("Table_3.13._Projects_with_IFC_Collaboration.xlsx", True),
    create_table_3_15: ("Table_3.15._PCM_Projects.xlsx", True),
    create_table_3_16: ("Table_3.16._Sectors_with_Active_PCM.xlsx", True),
    create_table_4_1:  ("Table_4.1._Importance_of_Context-Appropriate_Innovation.xlsx", True),
    create_table_D_1:  ("Table_D.1._Distribution_of_Innovation_in_WBG_portfolio.xlsx", True),
    create_table_D_2a: ("Table_D.2a._Innovation_Premium_Across_Projects_-.xlsx", True),
    create_table_D_2b: ("Table_D.2b._Innovation_Premium_Across_Projects_–_Bank_Performance_Rating.xlsx", True),
    create_table_D_2c: ("Table_D.2c._Innovation_Premium_Across_Projects_–_Quality_of_Supervision_Rating.xlsx", True),
    create_table_D_2d: ("Table_D.2d._Innovation_Premium_Across_Projects_–_Quality_at_Entry_Rating.xlsx", True),
    create_table_E_1:  ("Table_E.1._Selected_Examples_of_Innovation_Models_Generated_Based_on_the_Analytics.xlsx", True),
    create_table_E_2:  ("Table_E.2._Top_Four_Innovation_Models_by_Decade.xlsx", True),
    create_table_E_5:  ("Table_E.5._Diffusion_of_PPP_Model_Over_Time.xlsx", True),
    create_table_E_10: ("Table_E.10._Diffusion_of_CDD_Model_Over_Time.xlsx", True),
    create_table_F_1:  ("Table_F.1._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS.xlsx", False),
    create_table_F_2:  ("Table_F.2._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_Conditional_Cash_Transfers.xlsx", True),
    create_table_F_3:  ("Table_F.3._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_PPP.xlsx", True),
    create_table_F_4:  ("Table_F.4._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_E-Procurement.xlsx", True),
    create_table_F_5:  ("Table_F.5._Diffusion_of_Innovation_Models_in_FCS_vs._Non-FCS_CDD.xlsx", True),
}
